name: 'Test Common Lisp'
description: 'Run test of Common Lisp project using rove on Docker'
inputs:
  lisp:  # id of input
    description: 'Name of Common Lisp implementation'
    required: true
    default: 'sbcl-bin'
  runs:
    using: 'docker'
    image: 'test-docker/Dockerfile'
    args:
      - ${{ inputs.lisp }}
