on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lisp: [sbcl-bin ccl-bin]
    name: A job to test Common Lisp project
    steps:
    - name: Test step
      id: test
      uses: eshamster/try-cl-test-on-gh-actions@v0.1.1
      with:
        lisp: '${{ matrix.lisp }}'
